# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Myspleen
    url: https://www.myspleen.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /IsMyspleenDown
  logoUrl: https://www.myspleen.org/pic/logo.png
  name: Is Myspleen Down?
  introTitle: Myspleen Status Page
  introMessage: This status page checks Myspleen every 5 minutes
  navbar:
    - title: Status
      href: /
    - title: Myspleen
      href: https://www.myspleen.org/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
