owner: Hagabard # Your GitHub organization or username, where this repository lives
repo: IsMyspleenDown # The name of this repository

sites:
  - name: Myspleen
    url: https://www.myspleen.org

status-website:
  cname: status.myspleen.org
  logoUrl: https://www.myspleen.org/pic/logo.png
  name: Myspleen Status Page
  introTitle: Is Myspleen Down?
  introMessage: This status page checks Myspleen every 5 minutes
  theme: dark
